### ISSUE TITLE
Edit tag option making changes in UIN values in the home screen

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#148]
**Describe the bug**
Edit tag option making changes in UIN values on the VC card in the home screen

**To Reproduce**
1. Open app and head to home page
2. click on add ID and download VC
3. Go back to home
4. Open the downloaded VC
5. Click on the edit button on the top right corner
6. Enter the recuird value and click on save
7. Go back to home

**Expected behavior**
no changes should be happened in the UIN values on the card

**Current behavior**
Edit tag option making changes in UIN values on the VC card in the home screen

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/195092012-8a70a760-bb75-4668-b3b7-fdf5aefe57a2.png)

**Smartphone (please complete the following information):**
Device: android
MOSIP Version: 121
MOSIP server: qa-121.mosip.net
APK link : https://github.com/mosip/inji/suites/8476299188/artifacts/376688868

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: QA4_io.mosip.residentapp-0.4.1-beta.2-7-597814a-fix_214-218-250-sharing-prompts-newlogic_20221123_1526.apk

**WORKS AS EXPECTED**
CC: @kyanthony @pmigueld @danicaerediano 

**Screenshots**
![Screenshot_20221123-162400_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/203501318-7c0a218a-b668-4266-a97c-aa88e7ff175f.jpg)
![Screenshot_20221123-162404_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/203501335-7684d4e1-0069-45a3-a3d9-df6bb6a547bb.jpg)

**Additional context**
Issue registered for iOS: https://github.com/mosip/inji/issues/195

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: QA4_io.mosip.residentapp-0.4.1-rc1-newlogic_20221123_1723.apk

**WORKS AS EXPECTED**
CC: @kyanthony @pmigueld @danicaerediano

**Additional context**
Issue registered for iOS https://github.com/mosip/inji/issues/195

**Screenshot**
https://user-images.githubusercontent.com/102940764/203713355-0cefd9e2-d0a7-4c8b-8f4e-cf9ea94585fd.mp4
![Screenshot_20221124-143452_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/203713388-b6f84506-0f14-4ec0-b688-ce2031738cd4.jpg)
![Screenshot_20221124-143732_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/203713399-f0076545-fabc-41f2-bf62-25f06d6e1a5b.jpg)

**Comment by damodarguru** [comment]
Verified this issue in the new build, the issue is fixed, after edit tag option no changes happened in the UIN/VID values on the card, I am attaching the screenshot and the device details below for reference.
Screenshot:
![IMG_20230310_140151_1 (1)](https://user-images.githubusercontent.com/124761463/224265962-2b6f2c54-ad26-44d5-a5fb-45a7ddd3681d.jpg)
![IMG_20230310_140222_1](https://user-images.githubusercontent.com/124761463/224266018-698fcd2e-f7da-4db2-93c4-b1c816809736.jpg)
![image](https://user-images.githubusercontent.com/124761463/224274301-51d2d78f-83cb-4ca7-bf15-3a52610d4fe3.png)
![image](https://user-images.githubusercontent.com/124761463/224274359-ae2859d9-cb38-48c0-96f4-954f63bcff46.png)

Tested in;
Device: Redmi 7A
Android Version:10
BLE version :4.2
Inji app version: https://github.com/mosip/inji/actions/runs/4376897206

Device: Redmi K20 pro
Android Version: 11
BLE version :5.0
Inji app link: https://github.com/mosip/inji/actions/runs/4376878070
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net
