### ISSUE TITLE
iOS : CSS issues in purple themed app

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#397]
**Describe the bug**

1. MOSIP logo in starting screen / unlock screen is blur and is smaller in size when compared to orange theme.

![image](https://user-images.githubusercontent.com/79500509/211052146-b4f2ba00-00fa-4c08-b95d-de4109266959.png)

2. Get started button has two border lines at the bottom.

![image](https://user-images.githubusercontent.com/79500509/211052570-a2a188df-7c5d-4e58-9b18-69023c46c5c7.png)

3. Face icon while downloading VC is blur 

![image](https://user-images.githubusercontent.com/79500509/211052880-663c90e5-cfbc-4e7d-91ec-aa149270fad6.png)

4. MOSIP logo on VC in sharing screen is shifted from right corner to left corner.

![image](https://user-images.githubusercontent.com/79500509/211053527-1c5a9e0f-c90d-4042-9560-521d3e249b36.png)

5. Biometric toggle button in profile section color should be consistent across the app

![image](https://user-images.githubusercontent.com/79500509/211054533-946db2a1-d90a-407e-ac18-546db1d73c0e.png)

6. The cursor in Otp screen is still in orange

![image](https://user-images.githubusercontent.com/79500509/211055493-32f05c36-c4b7-44b2-8bbb-38aa0e4e9e8d.png)

7. Field name and resident data should have color contrast which can help user to quickly identity between data and field names.

![image](https://user-images.githubusercontent.com/79500509/211056379-e16ccd7c-a3bf-4139-b6a0-7b2dc6a8c9d0.png)

![image](https://user-images.githubusercontent.com/79500509/211056402-3edf0a03-a912-4ba0-9cff-96f2ae970ced.png)
 

**Smartphone (please complete the following information):**

- Device: iPhone 8 & iPhone 11
- OS: 16.0.2 (20A380), 15.6.1
- Inji app version: 0.4.1 (7) -> Testflight
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net

**Comment by vijay151096** [comment]
Most of the Issues Listed are fixed in the previous releases, and 
Here is the List of the left over issues that are fixed now :

**1. MOSIP logo in starting screen / unlock screen is blur and is smaller in size when compared to orange theme.**
<img width="422" alt="Screenshot 2023-03-21 at 5 05 45 PM" src="https://user-images.githubusercontent.com/94220135/226594792-6afcf550-685a-48d2-87d0-a05f94e171db.png">

**3. Face icon while downloading VC is blur** 
<img width="361" alt="Screenshot 2023-03-21 at 5 06 10 PM" src="https://user-images.githubusercontent.com/94220135/226594859-ad1968fe-12bb-4380-ba7a-c815883b1f16.png">

**5. Biometric toggle button in profile section color should be consistent across the app**

Purple Theme: 
<img width="420" alt="Screenshot 2023-03-21 at 5 06 45 PM" src="https://user-images.githubusercontent.com/94220135/226594974-cd27cef7-229b-443e-9e04-3c0306ec180a.png">

Orange Theme
<img width="418" alt="Screenshot 2023-03-21 at 5 07 55 PM" src="https://user-images.githubusercontent.com/94220135/226595218-ea6107eb-c1fc-4087-8b69-438e255dc040.png">

**Comment by Anushree09-N** [comment]
**Verified in :**
 iphone 8	| iphone 16 BLE 5.0

 **app commit id:** 
![image](https://user-images.githubusercontent.com/79500509/228137632-f20d8a2d-c91c-4413-ad75-6dfb3b668541.png)

**iOS app version** :0.4.1 (32)

![IMG20230328110358](https://user-images.githubusercontent.com/79500509/228138150-3915086b-22e8-4564-8ca2-3edf54d4dc41.jpg)

1. MOSIP logo in starting screen / unlock screen is not blur and is normal in size when compared to orange theme.

![image](https://user-images.githubusercontent.com/79500509/228214999-74ff31a1-ad85-497f-adf5-41613a901fd2.png)

2. Get started button has two border lines at the bottom.

![image](https://user-images.githubusercontent.com/79500509/228215686-8121a9d3-ddf3-47f5-b72a-dfcf37ca143d.png)

- Will raise separate minor bug

3. Face icon while downloading VC is not blur now.

![image](https://user-images.githubusercontent.com/79500509/228216923-a1ff6aa1-45f8-4f45-bb99-16044e7963f6.png)

5. MOSIP logo on VC in sharing screen is not shifted  to left corner.

![image](https://user-images.githubusercontent.com/79500509/228217011-695c75ef-f808-43b4-8cc2-a17e6a166536.png)

6. Biometric toggle button in settings page is now matched with app theme color 

![image](https://user-images.githubusercontent.com/79500509/228217275-af32e575-f0fc-4f8b-9825-ea4d316b666a.png)

![IMG20230328163843](https://user-images.githubusercontent.com/79500509/228217993-e0729d1d-06c6-4e24-81d2-d9629c304eeb.jpg)

7. The cursor in Otp screen is in purple now

![image](https://user-images.githubusercontent.com/79500509/228219067-b8bcaadf-028c-4654-b734-58b3cc20dfe4.png)

![image](https://user-images.githubusercontent.com/79500509/228219165-342db282-a17a-4a54-9a54-95ce5ced14e8.png)

8. Field name and resident data is having color contrast which can now help user to quickly identity between data and field names. And color is matched according to the app theme.

![image](https://user-images.githubusercontent.com/79500509/228219398-94a123af-4ca2-4fd1-a748-ae7aec75d71c.png)

![image](https://user-images.githubusercontent.com/79500509/228219446-4cacab2f-c3ab-4601-a85e-f8d25e4e55be.png)

Working as expected , hence closing
