### ISSUE TITLE
Incorrect labels on the iOS wallet

### ISSUE THREAD

**Issue by Alka1703** [mosip/inji#598]
In iOS wallet some of the labels need to be updated: 

1. On the **Consent** page in the top left, the label should say **Requested by Verifier** instead of **Request by Wallet**
2. On the **History** page, for each VC shared the label on top of it says **wallet** instead of **verifier**
3. When the VC is rejected by the verifier, the iOS wallet gets the message "Your ID was discarded by **wallet**" instead of "Your ID was discarded by **verifier**"
4. . When the VC is accepted by the verifier, the iOS wallet gets the message "Your ID has been successfully shared with **wallet**" instead of "Your ID has been successfully shared with **verifier**"

**Comment by vijay151096** [comment]
Fixed the incorrect device name( "Verifier" instead of "Wallet") labels in iOS.
<img width="947" alt="Screenshot 2023-03-02 at 4 13 20 PM" src="https://user-images.githubusercontent.com/94220135/222413391-981ae99d-76bc-45f3-acce-d8f1d77962df.png">
<img width="945" alt="Screenshot 2023-03-02 at 4 11 33 PM" src="https://user-images.githubusercontent.com/94220135/222413422-6cdd0534-489b-4dd2-80fd-7b609bbd082b.png">
<img width="945" alt="Screenshot 2023-03-02 at 4 12 00 PM" src="https://user-images.githubusercontent.com/94220135/222413430-472f71b3-c77c-445e-bca7-981e558dd4de.png">
<img width="946" alt="Screenshot 2023-03-02 at 4 12 21 PM" src="https://user-images.githubusercontent.com/94220135/222413441-680b4131-0dc9-43f5-8414-d8efaf29a703.png">

**Comment by vharsh** [comment]
The following change fixes the label on iOS Wallet from `wallet` to `Verifier` thus removing semantic confusion.

PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/29
PR for mosip/inji: https://github.com/mosip/inji/pull/615

The PRs have been merged in 06-03-2023 Release and the latest commit id on mosip/inji/develop is https://github.com/mosip/inji/commit/8867f3cc2dda5fb19c003f85524a8f5cfce61303
