### ISSUE TITLE
Label changes for Add ID and Request ID screens

### ISSUE THREAD

**Issue by nayakrounak** [mosip/inji#609]
**Problem Statement**

The labels in Add ID screen and Request ID (QR code) screen are not user-friendly.

**Resolution**

We should change the below labels in Add ID and Request ID (QR code) screens.

* Add ID
    * "Enter the MOSIP-provided UIN or VID of the ID you wish to retrieve" should be changed to "Enter your UIN/VID to download your card".
    * "Generate ID" can be changed to "Generate My Card"
    * When the user clicks on the option "Don't have your UIN/VID? Get it here" - the user is redirected to a new screen to get the UIN or VID. Here, the label, "To retrieve your UIN or VID, enter your application ID number" should be changed to "Enter your application ID number to get your UIN".
    * Information in the info icon near the Application ID, "Application ID Number is printed on the acknowledgement provided after enrollment" should be changed to "Application ID number is printed on the acknowledgement slip received during enrollment" 
* Request ID screen
    * The label "Show this QR code to request ID" should change.

**Screenshot**

![image](https://user-images.githubusercontent.com/44160407/222531580-bc84fadf-cc06-49a1-8fea-ab8d2efdbb0d.png)

![image](https://user-images.githubusercontent.com/44160407/222531699-32bb56b2-bdfb-4572-a6e1-0c85ba7b3e37.png)

**Comment by nayakrounak** [comment]
@SwatiPeriwal, Please share the label for "Share this QR code to request ID"

**Comment by adityankannan-tw** [comment]
@SwatiPeriwal, Can you please share the label for "Share this QR code to request ID".

**Comment by SwatiPeriwal** [comment]
Display this QR code to request resident ID

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by adityankannan-tw** [comment]
> Display this QR code to request resident ID Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)

Hello @SwatiPeriwal , Since we are moving from ID to Card as VC label as mentioned in issue - 607,  I have used the hardcoded ID value for Get UIN/VID screen, as it is making more sense to use Application ID instead of Application Card. Please confirm whether these changes are fine or let me know if there are changes required.

**Comment by SwatiPeriwal** [comment]
@nayakrounak To retrieve your UIN or VID, enter your application ID number" should be changed to "Enter your application ID number to get your UIN".

in the above sentence, can we trim the word "number" from application ID... because when we say application ID it means we are referring to a number...    Please confirm..

**Comment by SwatiPeriwal** [comment]
2. Information in the info icon near the Application ID, "Application ID Number is printed on the acknowledgement provided after enrollment" should be changed to "Application ID number is printed on the acknowledgement slip received during enrollment" ----------- needs update--- "Application ID is available in the acknowledgement received after enrolment."

**Comment by SwatiPeriwal** [comment]
3. Show this QR code to request ID  can be changed to "Display this QR Code to request resident ID".

**Comment by nayakrounak** [comment]
Yes, let's remove the word "number" from the text

**Comment by vharsh** [comment]
Label change requests for the texts have been acknowledged as mentioned in the
issue, some more changes need to be done for certain text-boxes during the VC
transfer phase.

PR for mosip/inji: https://github.com/mosip/inji/pull/630

The PRs have been merged in 09-03-2023 Release and the latest commit id on mosip/inji/develop is fa142c6

**Comment by vharsh** [comment]
@Anushree09-N All the changes requested for in this ticket have been acknowledged, it'd be helpful if a newer ticket is created for more label changes later on.

**Comment by Anushree09-N** [comment]
Verified in: 
Redmi 7A
Android 10
BLE 4.2

MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
app link: https://github.com/mosip/inji/actions/runs/4376897206

**Add ID screen**

1. "Enter the MOSIP-provided UIN or VID of the ID you wish to retrieve" is changed to "Enter your UIN/VID to download your card".

![image](https://user-images.githubusercontent.com/79500509/224657292-f107dff0-7466-490f-bee2-6554ee28cd60.png)

3. "Generate ID" is changed to "Generate My Card".

![image](https://user-images.githubusercontent.com/79500509/224657031-e6ff90d5-246f-4dce-afa9-2a8de6d9f7b1.png)

4. When the user clicks on the option "Don't have your UIN/VID? Get it here" - the user is redirected to a new screen to get the UIN or VID. Here, the label, "To retrieve your UIN or VID, enter your application ID number" is changed to "Enter your application ID number to get your UIN".

![image](https://user-images.githubusercontent.com/79500509/224656949-53b7cf65-d41d-4f43-824b-0797558a86c3.png)

5. Information in the info icon near the Application ID, "Application ID Number is printed on the acknowledgement provided after enrollment" is changed to "Application ID is available in the acknowledgement received after enrolment."

![image](https://user-images.githubusercontent.com/79500509/224656782-53cf6104-3b59-4261-98a8-c89a80a9199a.png)


**Request ID screen:**
1. Show this QR code to request ID can be changed to "Display this QR Code to request resident ID".

![image](https://user-images.githubusercontent.com/79500509/224656695-7a8bc132-4d22-4a03-9e70-5bd2b9364376.png)

@SwatiPeriwal  As discussed over call, ID is changed to Card across the app and hence Above scenario is also changed to Card instead of ID .

Commit Id of verified app: 
![image](https://user-images.githubusercontent.com/79500509/224631346-2f3d9305-f3ec-4c86-92f3-5389c6d742f6.png)

![image](https://user-images.githubusercontent.com/79500509/224631485-d9a1fd70-249a-4055-bfef-bb55b1531ebb.png)

**Comment by Kratitva** [comment]
This is fixed as part of release v0.9.1
