### ISSUE TITLE
Redmi 7A and iphone7 getting disconnected 

### ISSUE THREAD

**Issue by Alka1703** [mosip/inji#667]
**Describe the bug**
The VC transfer is failing with big VC transfer

**To Reproduce**

1. Use Redmi 7A phone acting as a Verifier
2. Use  iPhone7 as a Wallet
3. Initiate a large VC transfer

The `Transfer Error `message is shown

**Expected behavior**

- VC Transfer should happen as expected

**Actual behavior**

- VC transfer is failing intermittently

**Smartphone (please complete the following information):**

- Verifier Device: 
  - Phone make/model: Vivo Y73
  - OS: Android 12
  - BLE version : 5.0

- Wallet Device: 
  - Phone make/model: iPhone 7
  - OS: iOS 15
  - BLE version : 5.0

**Comment by krishnakumar4a4** [comment]
This device combination is reported as part of #548 issue. https://github.com/mosip/inji/issues/548#issuecomment-1456144926

For a smaller VC, this problem is not seen. For larger VCs of greater than 500KB (uncompressed 700KB) size, it is observed that the current failure frame retry limit of 5 is not enough. 
Hence, As part of #668 we are increasing the failure frame limit to 15 to accommodate this device combination.

**Comment by krishnakumar4a4** [comment]
The fix is implemented as part of #668 is given in 24-03-2023 release:

INJI PR link: https://github.com/mosip/inji/pull/670
Tuvali PR link: https://github.com/mosip/tuvali/pull/49

**Comment by Raginikrishnamurthy** [comment]
Verified this bug as part of https://github.com/mosip/inji/issues/668, hence closing this bug.
