### ISSUE TITLE
Scan QR code Error in iOS release build

### ISSUE THREAD

**Issue by jannahadlaon** [mosip/inji#74]
Error pops up (Flight mode must be disabled for the scanning functionality) even if the device is not in flight mode. Camera does not activate 

**To Reproduce**

1. Go to SCAN (second icon from left)
2. See error

**Expected behavior**
Camera should activate and can scan QR code

**iOS release build**
Version 0.4.0 (1.0.0)

**Screenshots**
![IMG_1536](https://user-images.githubusercontent.com/102940764/185056119-ebe99f3a-c59a-4cb0-a768-e77af007010d.png)

**Comment by kneckinator** [comment]
@kyanthony @pmigueld what is the status of this issue?

**Comment by pmigueld** [comment]
@kneckinator there's already a fix, just need to open a PR. It will change the button in iOS to redirect to the app settings since we can't turn off flight mode directly in the app (iOS restriction). I'll document this behavior [here](https://docs.google.com/document/d/1KFoDK0s6tmy3erafPzHaSBGn-L7Rb--UW9Y_3KGUMq8/edit#heading=h.fpw8915ir7cj).

**Comment by jannahadlaon** [comment]
Tested this ticket on **iOS** build version 0.4.0 (6) and issue is still present.
Ticket has been assigned back to dev @pmigueld.

**Steps to reproduce the behavior:**
1. Go to SCAN (second icon from left)
2. See error

**Devices**
iPhone SE (iOS 15.4)
iPhone 11 (iOS 15.5)

**Comment by pmigueld** [comment]
@jannahadlaon this is caused by your test device having no SIM card according to the documentation of the library we use:

![image](https://user-images.githubusercontent.com/1631922/190131914-66c7279d-f77e-406c-9e1b-ae5cc1aa0a60.png)
Source: https://github.com/c19354837/react-native-system-setting

I don't see a quick fix for now since this seems to be a limitation in iOS.

**Comment by jannahadlaon** [comment]
Tested on **iOS build version 0.4.0 (6.3)**
**Devices**: 
iPhone11 
iPhone SE

**WORKS AS EXPECTED**

**Comment by pmigueld** [comment]
Flight check removed since it's not the cause of the original issue here: https://github.com/idpass/inji/issues/103
