### ISSUE TITLE
Resident phone remains in sharing state when Banker's phone gets disconnected to some reason like network issue .

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#96]
**Describe the bug**
Resident phone remains in sharing state when Banker's phone gets disconnected to some reason like network issue .

**Prerequisite** 
device A (requesting): Bluetooth enabled and device B ( Resident phone sharing): Bluetooth, location and camera access: enabled

**To Reproduce**
1. On device A, go to REQUEST (third icon from left) - verify qr code is displayed and message is correct 

2. On device B, go to SCAN (second icon from left) - verify camera is activated 

3. On device B, scan QR code displayed on device A – verify device B displays “Connecting…” 

4. Device A should display “Connected to device. Waiting for VID…”. Device B should display “Sharing VID” card 

5. Enter text on “Reason for sharing (optional)” and click “Accept request and choose VID” 

6. Device B should display card with list of possible VC to share. No VC should be preselected. “Share” button should only be activated when a VC has been selected. Name of receiving device should be displayed. 

7. Bankers phone disconnected with error “The connection was interrupted.please try again“

**Current behavior**
phone stuck with sharing screen unable to switch back to previous screen untill we close the app and re login to Mobile App.

**Expected behavior**
App should switch back to previous screen.

**Screenshots**
![WhatsApp Image 2022-06-07 at 2 50 10 PM](https://user-images.githubusercontent.com/79500509/188618958-dcf23d63-7353-4aa1-883c-9b9ad9f71c34.jpeg)
![WhatsApp Image 2022-06-07 at 2 50 17 PM](https://user-images.githubusercontent.com/79500509/188618962-9b88554a-3551-4c8e-9e5a-88136aaf0862.jpeg)

**Smartphone (please complete the following information):**
- Device: Android
- Inji app version: [e.g 0.3.0]
- Mimoto version: [e.g 1.2.x]
- MOSIP Version: [e.g. 1.2.1]
- Mimoto server: [e.g. https://.....com]
- MOSIP server: [e.g. https://...mosip.com]

**Additional context**
apk details: 0.3.0-rc5-dirty-newlogic
Qa env details: QA4(1.2.1)

**Comment by jannahadlaon** [comment]
While testing ticket [[ICA-96]](https://github.com/mosip/inji/issues/96), i can verify that we have a `Cancel` button below `Sharing...` if the sharing takes longer than expected so it will no longer get stuck in sharing state when the receiving device is disconnected (because we have the option to cancel the sharing)

However,
**Scenario 1**: Sharing device cancelled sharing ([https://github.com/mosip/inji/issues/249](url))
- when the Cancel button is click during sharing, no prompt is displayed on the receiving device that the sharing was cancelled.
- ID is still shared (received)
- `History` on the receiving device shows that the ID has been received.
- `History` on the sharing device does not display the shared ID that was cancelled

**Scenario 2**: Receiving device clicked on `Cancel` while `Exchanging device info...` ([https://github.com/mosip/inji/issues/250])(url)
- no prompt is displayed on the sharing device that the sharing was cancelled.

cc: @kyanthony @pmigueld

**Comment by santhoshsunder** [comment]
Tested this issue in the BLE build (le730bf), irrespective of disabling mobile data and wifi ble protocol lets the user share the VC, hence this scenario with the network issue becomes irrelevant, closing the bug
